def includeme(config):
	config.add_static_view('static', 'static', cache_max_age=3600)
	config.add_route('home', '/')
	config.add_route('calculate_payrate', '/calculate_payrate')
	config.add_route('employee_add','/employee_add')
	config.add_route('employee_save','/employee_save')
	config.add_route('save_payslip','/save_payslip')
	config.add_route('save_leave','/save_leave')
	config.add_route('send_guard_reminder','/send_guard_reminder')
	config.add_route('send_email_to_guards','/send_email_to_guards')
	config.add_route('save_bulk_employee','/save_bulk_employee')
	config.add_route('search_employee','/search_employee')
	config.add_route('fetch_employee','/fetch_employee')