def includeme(config):
	config.add_static_view('static', 'static', cache_max_age=3600)
	config.add_route('home', '/')
	config.add_route('calculate_payrate', '/calculate_payrate')
	config.add_route('employee_add','/employee_add')
	config.add_route('employee_save','/employee_save')
	config.add_route('save_payslip','/save_payslip')
	config.add_route('save_leave','/save_leave')
	config.add_route('send_guard_reminder','/send_guard_reminder')
	config.add_route('send_email_to_guards','/send_email_to_guards')
	config.add_route('save_bulk_employee','/save_bulk_employee')
	config.add_route('search_employee','/search_employee')
	config.add_route('fetch_employee','/fetch_employee')
	config.add_route('delete_employee','/delete_employee')
	config.add_route('update_employee','/update_employee')
	config.add_route('view_employee','/view_employee')
	config.add_route('edit_employee','/edit_employee')
	config.add_route('login','/login')
	config.add_route('logout','/logout')
	config.add_route('confirm_user_registration','/confirm_user_registration')
	config.add_route('register','/register')
	config.add_route('log_user','/log_user')
	config.add_route('payslip','/payslip')
	config.add_route('send_payslip','/send_payslip')
	config.add_route('save_updated_employee','/save_updated_employee')
	config.add_route('delete_employee_from_database','/delete_employee_from_database')
	